### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by tigerfoot** [kilobyte/termrec#5]
With 146 commit since 0.17 perhaps a 0.18 release would be cool ?
;-)

**Comment by kilobyte** [comment]
Well, yeah, probably — there's especially a bunch of display corruption bugs.

I wanted to carefully think about the API before declaring it stable, then got busy with unrelated stuff around Debian's freeze.  It went nasty when not even responding to Mykola Grechukh's pull request ended up looking very rude.  That wasn't my best day...

So you're right, I should get around to wrapping it up.  But then, I got a reproducible btrfs bug at hand to report, a couple of packages to upload, etc, etc.  So I can't promise a timely release :(

**Comment by kilobyte** [comment]
Finally done 3 months ago...
